### ISSUE TITLE
Expose functionlike macro invocation

### ISSUE THREAD

**Issue by reinerp** [casey/boilerplate#35]
This library is great! I really like the simplicity and power of directly using Rust syntax for control flow. 

I would like to use the templating with an inline string, and without needing to define a custom struct. Using the `MyTemplateTxt` example from your README, it would become something like this:

```
fn my_template(foo: bool, bar: Result<String, Box<dyn std::error::Error>>) -> String {
  boilerplate!(r#"
%% if foo {
Foo was true!
%% }
%% match bar {
%%   Ok(ok) => {
Pretty good: {{ ok }}
%%   }
%%   Err(err) => {
Not so great: {{ err }}
%%   }
%% }
"#)
}
```

In fact, I independently developed a similar library to boilerplate, which uses exactly this approach, see example: https://github.com/reinerp/utemplate/blob/main/utemplate/examples/simple.rs. But I think I prefer your template syntax to mine!

There's a few advantages to the functionlike macro approach:

1. The user doesn't need to define a `struct` for each template they care about. Instead, variable reference from templates are picked up from context. This allows things like global constants `const SOME_CONSTANT: &str` as well.
2. The template is more powerful, allowing other aspects of control flow such as early returns. For example:

     ```
     fn format_all(foos: &[Result<usize, Box<dyn std::error::Error>>]) -> Result<String, Box<dyn std::error::Error>> {
       boilerplate!(r#"
     %%  for foo in foos {
     %%    let f = foo?;  // Note early return here.
           The next value is {{f}}.
     %%  }
     "#)
     }  
     ```
3. The procmacro implementation is simpler. In particular, you don't need to parse the `struct` type (so you don't need `syn` as a dependency), and you don't need to handle generics (which are often a pain).

**Comment by casey** [comment]
Glad you like the library! And very cool that you also came up with the same approach. It's very powerful for how simple it is.

I just implemented this, and it was surprisingly easy. `String` and `Formatter` both implement `std::fmt::Write`, so basically no changes to the core implementation were required, I just had to add a function-like proc macro and add some plumbing. I think that's kind of the theme of this library, surprisingly powerful and surprisingly simple.

This is a great addition to the library, thanks so much for opening this issue and suggesting it. I just released 0.2.5 with the new proc macro.

I didn't make `syn` optional, but easily could if that's something that someone wants.
