### ISSUE TITLE
Include a sub-template.

### ISSUE THREAD

**Issue by dan-da** [casey/boilerplate#42]
Let's say my template is an html page and I want to include a header and a footer with common elements.

How can I best achieve this?

I tried using include_str within the template, eg:

```
%% include_str!("path-to-header.html")
```

But that results in parse error.

Suggestions:
1. provide an example in the docs how to do include a sub-template using existing code.  
2. consider adding a mechanism for doing this within a template file without need to touch the non-template rust code.

**Comment by casey** [comment]
You can `include_str!` to work like so:

```
{{ Trusted(include_str!("path-to-header.html")) }}
```

`%%` is for statements which execute code, `$$` and `{{…}}` is for values to be interpolated into the template. `Trusted(…)` is needed to avoid escaping the internal HTML content.

I think the best way to do this is actually to use a nested template, I just added [an example](https://github.com/casey/boilerplate/blob/da7d7fab10919476b0c9f00f7f8999ee81c07b27/src/lib.rs#L4340) showing how to do this.

**Comment by dan-da** [comment]
thx for the examples.      I think your example link is broken.  this works.  https://github.com/casey/boilerplate/blob/da7d7fab10919476b0c9f00f7f8999ee81c07b27/src/lib.rs#L434
